<!DOCTYPE html>
<html lang=ja>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>ex0104h.php</title>
</head>
<body>
	<form method="get" action="ex0104.php">
	<h2>血液占い</h2>

		<label>あなたの血液型を入力してください
		<select name="browser">
				<option disabled="disabled">あなたの血液型</option>
				<option  value="A">A型</option>
				<option  value="B">B型</option>
				<option  value="AB">AB型</option>
				<option  value="O">O型</option>
				<option  value="">わからない</option>
		</select>
		</label> <input type="submit" value="占う" name="sub1" />
	</form>
</body>
</html>