<!DOCTYPE html>
<html lang=ja>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>ex0201h.php</title>
</head>
<body>
<form method="post" action="ex0202.php">
<p>曜日の表現</p>

<p><label><input type="radio" name="radio1" value="en" >英語表示</label></p>
<p><label><input type="radio" name="radio1" value="jpn" >日本語表示</label></p>
<P><input type="submit" value="表示" name="sub1" ></p>
</form>
</body>
</html>
