<!DOCTYPE html>
<html lang=ja>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>課題2-3</title>
<style type="text/css">
ul li {
	list-style: none;
	margin-top: 10px;
}
</style>
</head>
<body>
<p>金額の計算</p>
<form method="get" action="ex0203.php">
<ul>
<li><label>単価<input type="text" name="price" /></label></li>
<li><label>数量<input type="text" name="qty" /></label></li>
<li><input type="submit" value="計算" name="sub1"/></li>
</ul>
</form>
</body>
</html>